In [1]:
%matplotlib inline  

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/mlbc5full-train.csv', sep=';', index_col='id')

In [4]:
df.head()

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
id                                                                          
0   18393       2     168    62.0    110     80            1     1      0   
1   20228       1     156    85.0    140     90            3     1      0   
2   18857       1     165    64.0    130     70            3     1      0   
3   17623       2     169    82.0    150    100            1     1      0   
4   17474       1     156    56.0    100     60            1     1      0   

    alco  active  cardio  
id                        
0      0       1       0  
1      0       1       1  
2      0       0       1  
3      0       1       1  
4      0       0       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70000 entries, 0 to 99999
Data columns (total 12 columns):
age            70000 non-null int64
gender         70000 non-null int64
height         70000 non-null int64
weight         70000 non-null float64
ap_hi          70000 non-null int64
ap_lo          70000 non-null int64
cholesterol    70000 non-null int64
gluc           70000 non-null int64
smoke          70000 non-null int64
alco           70000 non-null int64
active         70000 non-null int64
cardio         70000 non-null int64
dtypes: float64(1), int64(11)
memory usage: 6.9 MB


In [6]:
df['gender'].value_counts()

1    45530
2    24470
Name: gender, dtype: int64

In [7]:
df[df['gender'] == 1].describe()

age   gender        height        weight         ap_hi  \
count  45530.000000  45530.0  45530.000000  45530.000000  45530.000000   
mean   19510.124577      1.0    161.355612     72.565605    128.139249   
std     2432.024493      0.0      7.052726     14.238838    158.054522   
min    10859.000000      1.0     55.000000     21.000000   -140.000000   
25%    18040.000000      1.0    157.000000     63.000000    120.000000   
50%    19726.000000      1.0    161.000000     70.000000    120.000000   
75%    21330.000000      1.0    166.000000     80.000000    140.000000   
max    23701.000000      1.0    250.000000    200.000000  16020.000000   

              ap_lo   cholesterol          gluc         smoke          alco  \
count  45530.000000  45530.000000  45530.000000  45530.000000  45530.000000   
mean      94.522776      1.384735      1.235054      0.017856      0.025500   
std      174.776855      0.693417      0.582956      0.132431      0.157639   
min      -70.000000      1.000000      1.000000      0.000000      0.000000   
25%       80.000000      1.000000      1.000000      0.000000      0.000000   
50%       80.000000      1.000000      1.000000      0.000000      0.000000   
75%       90.000000      2.000000      1.000000      0.000000      0.000000   
max    11000.000000      3.000000      3.000000      1.000000      1.000000   

             active        cardio  
count  45530.000000  45530.000000  
mean       0.802021      0.496727  
std        0.398481      0.499995  
min        0.000000      0.000000  
25%        1.000000      0.000000  
50%        1.000000      0.000000  
75%        1.000000      1.000000  
max        1.000000      1.000000

In [8]:
df[df['gender'] == 2].describe()

age   gender        height        weight         ap_hi  \
count  24470.000000  24470.0  24470.000000  24470.000000  24470.000000   
mean   19392.097875      2.0    169.947895     77.257307    130.078872   
std     2529.752770      0.0      7.228895     14.187636    146.186152   
min    10798.000000      2.0     65.000000     10.000000   -150.000000   
25%    17502.000000      2.0    165.000000     68.000000    120.000000   
50%    19655.500000      2.0    170.000000     75.000000    120.000000   
75%    21321.000000      2.0    175.000000     85.000000    140.000000   
max    23713.000000      2.0    207.000000    200.000000  14020.000000   

              ap_lo   cholesterol          gluc         smoke          alco  \
count  24470.000000  24470.000000  24470.000000  24470.000000  24470.000000   
mean     100.551982      1.333633      1.210462      0.218880      0.106375   
std      211.557292      0.653764      0.551493      0.413496      0.308323   
min        0.000000      1.000000      1.000000      0.000000      0.000000   
25%       80.000000      1.000000      1.000000      0.000000      0.000000   
50%       80.000000      1.000000      1.000000      0.000000      0.000000   
75%       90.000000      1.000000      1.000000      0.000000      0.000000   
max    10000.000000      3.000000      3.000000      1.000000      1.000000   

             active        cardio  
count  24470.000000  24470.000000  
mean       0.806906      0.505231  
std        0.394734      0.499983  
min        0.000000      0.000000  
25%        1.000000      0.000000  
50%        1.000000      1.000000  
75%        1.000000      1.000000  
max        1.000000      1.000000

45530 женщин и 24470 мужчин

In [9]:
df['alco'].unique()

array([0, 1])

In [10]:
df[(df['alco'] == 1) & (df['gender'] == 1)].shape[0]/\
df[df['gender'] == 1].shape[0]

0.02549967054689216

In [11]:
df[(df['alco'] == 1) & (df['gender'] == 2)].shape[0]/\
df[df['gender'] == 2].shape[0]

0.10637515324887617

In [12]:
df['smoke'].unique()

array([0, 1])

In [13]:
np.round(df[(df['smoke'] == 1) & (df['gender'] == 2)].shape[0]/\
df[df['gender'] == 2].shape[0]/\
(df[(df['smoke'] == 1) & (df['gender'] == 1)].shape[0]/\
df[df['gender'] == 1].shape[0]))

12.0

In [14]:
np.round((df[df['smoke'] == 0].age.median() - \
          df[df['smoke'] == 1].age.median())/30.4)

20.0

In [15]:
df['age_years'] = df['age'].apply(lambda x: np.round(x/365.25))

In [16]:
df['cardio'].unique()

array([0, 1])

In [19]:
def score(ap_hi_low_, ap_hi_hi_, chol_):
    return (df[(df['age_years'] >= 60) &
              (df['age_years'] <= 64) &
              (df['gender'] == 2) &
              (df['cholesterol'] == chol_) &
              (df['smoke'] == 1) &
              (df['ap_hi'] >= ap_hi_low_) &
              (df['ap_hi'] < ap_hi_hi_)].cardio.mean())

In [20]:
np.round(score(160, 180, 3) / score(0, 120, 1))

3.0

In [19]:
df['bmi'] = df['weight'] / (df['height'] * df['height'] / 100 / 100)

In [20]:
df['bmi'].median() 

#Медианный BMI по выборке лежит в пределах нормы 
# NOPE

26.374068120774975

In [21]:
df[df['gender'] == 1].bmi.mean()

27.98758344183312

In [22]:
df[df['gender'] == 2].bmi.mean()

26.75444235728947

In [23]:
# У женщин в среднем BMI выше, чем у мужчин
# YEAP

In [24]:
df[df['cardio'] == 1].bmi.mean()

28.566060627015435

In [25]:
df[df['cardio'] == 0].bmi.mean()

26.54817520679475

In [26]:
# У здоровых в среднем BMI выше, чем у больных
# NOPE

In [27]:
df[(df['cardio'] == 0) &
  (df['alco'] == 0) &
  (df['gender'] == 1)].bmi.mean()

26.845406594131518

In [28]:
df[(df['cardio'] == 0) &
  (df['alco'] == 0) &
  (df['gender'] == 2)].bmi.mean()

25.872638075460173

In [139]:
# В сегменте здоровых и непьющих мужчин BMI ближе к норме, 
# чем в сегменте здоровых и непьющих женщин
# YEAP

In [31]:
df_clean = df[(df['ap_hi'] > df['ap_lo']) & 
             (df['height'] >= df['height'].quantile(.025)) &
             (df['height'] <= df['height'].quantile(.975)) &
             (df['weight'] >= df['weight'].quantile(.025) )&
             (df['weight'] <= df['weight'].quantile(.975)) ]

In [35]:
np.round((1 - df_clean.shape[0] / df.shape[0]) * 100)

10.0